# Generated by Django 5.2.17 on 2026-09-13 11:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
