# Generated by Django 5.2.17 on 2026-09-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0002_alter_place_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='smart_searc_name_162fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['created_at'], name='smart_searc_created_dc6b32_idx'),
        ),
    ]
