# Generated by Django 5.2.17 on 2026-09-14 14:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'graph_nodes',
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='navigation.graphnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='navigation.graphnode')),
            ],
            options={
                'db_table': 'graph_edges',
                'constraints': [models.UniqueConstraint(fields=('from_node', 'to_node'), name='unique_graph_edge')],
            },
        ),
    ]
